apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: guyexpressaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guyexpressaks 
    spec:
      containers:
        - name: guyexpressaks 
          image: shasb.azurecr.io/guyexpressaks 
          ports:
          - containerPort: 3000